version: "3.7"
services:
  postgres:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - "./data/postgres-13:/pgdata"
      - "./data/dumps:/dumps"
    ports:
      - "${POSTGRES_PORT}:5432"
